services:
  postgres:
    image: postgres:15
    container_name: byteevents-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: byteevents
      POSTGRES_USER: byteevents_user
      POSTGRES_PASSWORD: byteevents_password
    ports:
      - "5433:5433"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:6-alpine
    container_name: byteevents-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local