version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: simple-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: byteevents
      POSTGRES_USER: byteevents_user
      POSTGRES_PASSWORD: byteevents_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: simple-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3333
      DATABASE_URL: postgresql://byteevents_user:byteevents_password@postgres:5432/byteevents
    ports:
      - "3333:3333"
    depends_on:
      - postgres
    volumes:
      - ./uploads:/app/uploads

volumes:
  postgres_data:
    driver: local
