services:
  - type: web
    name: byteevents-backend
    env: node
    plan: starter
    buildCommand: npm ci && npm run build
    startCommand: ./start-render.sh
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
